# Generated by Django 5.1.1 on 2025-01-06 13:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_project_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="github_link",
        ),
        migrations.RemoveField(
            model_name="project",
            name="icon",
        ),
        migrations.RemoveField(
            model_name="project",
            name="num_high_issues",
        ),
        migrations.RemoveField(
            model_name="project",
            name="num_low_issues",
        ),
        migrations.RemoveField(
            model_name="project",
            name="num_med_issues",
        ),
        migrations.RemoveField(
            model_name="project",
            name="team",
        ),
        migrations.RemoveField(
            model_name="project",
            name="token",
        ),
        migrations.RemoveField(
            model_name="project",
            name="user",
        ),
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.TextField(default="No description provided"),
        ),
        migrations.AddField(
            model_name="project",
            name="owner",
            field=models.ForeignKey(
                default=django.utils.timezone.now,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_projects_app",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="repository_url",
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="users",
            field=models.ManyToManyField(
                related_name="projects_app", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
