# Generated by Django 5.1.1 on 2024-10-13 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("github_link", models.CharField(max_length=30)),
                ("icon", models.CharField(max_length=30)),
                ("num_high_issues", models.BigIntegerField()),
                ("num_med_issues", models.BigIntegerField()),
                ("num_low_issues", models.BigIntegerField()),
                ("token", models.CharField(max_length=30)),
                ("team", models.CharField(max_length=30)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vulnerability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("file_location", models.CharField(max_length=30)),
                ("line", models.BigIntegerField()),
                ("vuln_id", models.CharField(max_length=30)),
                ("severity", models.CharField(max_length=30)),
                ("summary", models.CharField(max_length=200)),
                ("confidence", models.DecimalField(decimal_places=2, max_digits=3)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.project"
                    ),
                ),
            ],
        ),
    ]
